### ISSUE TITLE
What is your pycuda version and python version?

### ISSUE THREAD

**Issue by HuaZheLei** [yelantingfeng/pyLucid#2]
I use a  pycuda-2018.1 and python 2.7, but when I run the code, I always get a error:
pycuda.driver.CompileError: nvcc compilation of /tmp/tmpY94Kcb/kernel.cu failed
[command: nvcc --cubin -arch sm_70 -I/usr/local/lib/python2.7/dist-packages/pycuda/cuda kernel.cu]
[stderr:
nvcc fatal   : Value 'sm_70' is not defined for option 'gpu-architecture'
].
And I can not solve this problem from google.

**Comment by yelantf** [comment]
This is an issue should be posted in pycuda repository. I think the problem may be caused by a too old cuda version.
