### ISSUE TITLE
The results generated by pylucid are not as good as that generated by the official matlab code, Is there anything ignored?

### ISSUE THREAD

**Issue by yougoforward** [yelantingfeng/pyLucid#6]
The pylucid code run much faster. But I found the generated images and annotations always keep the same within continuous frames. The results may be not enough diverse.

**Comment by yelantf** [comment]
The basic logic of this codes is the same as the officially released matlab codes.  I think the same issue may appear in the images generated by official codes. If you find some critical difference which causes this issue,   feel free to reopen this issue.
