### ISSUE TITLE
向您请教如何部署环境呀

### ISSUE THREAD

**Issue by viever** [yelantingfeng/pyLucid#7]
请问您是在什么操作系统平台建立环境的？win or linux or mac？
我在windows 10  conda 虚拟环境中建立该项目所需要的环境，一直没法成功，参照了网上其他人安装pycuda的方法，最后得到的错误提示如下：pytools.prefork.ExecError: error invoking 'nvcc --preprocess -arch sm_52 -m64 -Id:\anaconda3\envs\pylucid\lib\site-packages\pycuda\cuda C:\Users\yangd\AppData\Local\Temp\tmpok_wmx4n.cu --compiler-options -EP': [WinError 2] 系统找不到指定的文件。
pycuda ，opencv,numpy ，ms c++14.0 cudatoolkit 等我都安装好了。现在好像是提示显卡驱动没安装，
您有什么更好的建议吗？期待您的回信，谢谢

**Comment by yelantf** [comment]
This repository was tested on a linux server (Ubuntu 16.04) and I am not sure if it will work on windows. Please make sure that pycuda works on your machine and I think it should be better if you seek for help in the pycuda repository.
